### PR TITLE
changed: deincrement saturation and lightness

### PR DESCRIPTION
**Pull request by ncaq**
I can not read character of saturation high yellow background color.
screenshot-2018-02-27-19-34-12

I think there are various opinions about numerical values.
100 and 40 will not work with the current algorithm.
I can not read the characters.

### CODE REVIEW

**Comment by jaspervdj** [comment]
Thanks!  Can you also put a screenshot here of the new colour scheme so people can see how it changed?

**Comment by ncaq** [comment]
I deleted the profile I applied earlier.
So I took a new profile and took a screenshot.
old
new
Is it slightly too dark? I am just about this.
However, I think that it is better to read the letters than before.
If you change it, make the text color brighter from `#ddd` and raise the saturation of the background a little more.

**Comment by jaspervdj** [comment]
So I think the tree navigator on the left looks a lot better and easier to read.  However, the visual browser on the right looks much more muted and it's harder to tell the different sections apart.

I'm not sure what the right solution is.  Some thoughts:

- We could use more muted colors for the tree navigator, and brighter variations of the same color for the visual browser.  But then we lose the consistency.
- We could do text in black and increase the overall brightness of the colors?
- We could do the text in black *or* white depending on the background color?  I think this would look fairly weird though.

**Comment by ncaq** [comment]
> We could use more muted colors for the tree navigator, and brighter variations of the same color for the visual browser. But then we lose the consistency.

It seems to be nice but it is certainly a matter of losing consistency

> We could do text in black and increase the overall brightness of the colors?

Since the current overall background color is black
When letter color is black
It seems necessary to turn the whole background color white

> We could do the text in black or white depending on the background color? I think this would look fairly weird though.

That's too strange
It surely becomes confused

# Compromise

Let me brighten the letter color for the time and lower only the brightness

**Comment by ncaq** [comment]
It's about this
screen shot 2018-03-02 at 16 39 16-fullpage
It seems that it can be read and looks good

**Comment by jaspervdj** [comment]
Yep, thanks!

**Pull request merged**
