### PR TITLE
Expose two modules as a library

### PR DESCRIPTION
**Pull request by adinapoli**
Hey @jaspervdj!

Long time no chat! Me and @adamgundry have been working on integrating Profiteur's renderer [into eventlog2html](https://github.com/adamgundry/eventlog2html/pull/3), and in order to do that, we piggybacked on the `profileToCostCentre` function and the `NodeMap` data structure. In order to import those from `eventlog2html`, we had to add a `library` stanza to the `.cabal` file and expose the `profileToCostCentre` function, which is what this PR does.

Let us know what you think!

### CODE REVIEW

**Comment by jaspervdj** [comment]
Hey @adinapoli!  That's awesome, this looks good to me.

**Review by jaspervdj — APPROVED** [review]

**Comment by adinapoli** [comment]
Thanks for the quick turnaround! 

Do you think this deserves a new `profiteur` Hackage release? I'm perfectly OK with just adding the `source-repository-package` dependency to `eventlog2html` by pointing to a git SHA, but I'm not sure what can be considered sufficiently "authoritative" at this point -- would current HEAD suffice?

**Comment by jaspervdj** [comment]
@adinapoli I wanted to merge the other open PRs as well before cutting a release.  I'm done with that now, and this is on Hackage as `v0.4.7.0`.

**Comment by adinapoli** [comment]
Splendid!

Many thanks :)

**Pull request merged**
